# CHAPTER-1: Vectors, Matrices, and Arrays

In [88]:
import numpy as np

## 1.1 creating vectors(horizontal & vertical)

In [89]:
vec_row = np.array([1,2,3])
vec_row

array([1, 2, 3])

In [90]:
vec_col = np.array([[1],[2],[3]])
vec_col

array([[1],
       [2],
       [3]])

## 1.2 creating a matrix

In [91]:
mat = np.array([[1,2],
               [2,3],
               [3,4]])

print('type of mat is:',type(mat))
mat

type of mat is: <class 'numpy.ndarray'>


array([[1, 2],
       [2, 3],
       [3, 4]])

In [92]:
mat_object = np.mat([[1,2],
                     [2,3],
                     [3,4]])

print('type of mat_object is:',type(mat_object))
mat_object

type of mat_object is: <class 'numpy.matrix'>


matrix([[1, 2],
        [2, 3],
        [3, 4]])

## 1.3 Sparse Matrix 

To represnt non-zero elements of a dataset efficiently. saprse matrix stores only non-zero elements and assume all the elements as zero thus helps in significat computational savings.

In [93]:
from scipy import sparse

In [94]:
matrix = np.array([[0,0],
                    [0,1],
                    [3,0]])
sparse_mat = sparse.csr_matrix(matrix)
# CSR- Compressed Sparse Matrix

In [95]:
sparse_mat
print(sparse_mat)
# (1,1) and (2,0) represent the indices of non-zero matrix values

  (1, 1)	1
  (2, 0)	3


## 1.4 Selecting elements

In [96]:
vec_row[1]

2

In [97]:
mat[1,1]

3

In [98]:
mat[0,0]

1

In [99]:
vec_row[:2]

array([1, 2])

In [100]:
vec_row[:]

array([1, 2, 3])

In [101]:
vec_row[-2]

2

In [102]:
mat[:,:]

array([[1, 2],
       [2, 3],
       [3, 4]])

In [103]:
mat[:,:1]

array([[1],
       [2],
       [3]])

In [104]:
mat[1:,:]

array([[2, 3],
       [3, 4]])

## 1.5 Describing a mtrix

In [105]:
mat.shape

(3, 2)

In [106]:
mat.size
# no of elements (rows*columns)

6

In [107]:
# no of dimensions - 2D array
mat.ndim

2

## 1.6 Applying operations to elements

In [108]:
op_mat = np.array([[9,5,7],
                 [4,1,6],
                 [2,3,7]])
op_mat

array([[9, 5, 7],
       [4, 1, 6],
       [2, 3, 7]])

In [109]:
add_hundred = lambda i : i + 100
# lambda is an object behaving like a function(anonymous function)

vec_add_hundred = np.vectorize(add_hundred)
# to create vectorized function

vec_add_hundred(op_mat)

array([[109, 105, 107],
       [104, 101, 106],
       [102, 103, 107]])

In [110]:
op_mat+100

array([[109, 105, 107],
       [104, 101, 106],
       [102, 103, 107]])

## 1.7 Finding the Maximum and Minimum Values

In [111]:
np.max(op_mat)

9

In [112]:
np.min(op_mat)

1

In [113]:
np.max(op_mat,axis=0)
# max value in each column

array([9, 5, 7])

In [114]:
np.max(op_mat,axis=1)
# max value in each row

array([9, 6, 7])

In [115]:
np.min(op_mat,axis=1)
# min value in each row

array([5, 1, 2])

In [116]:
np.min(op_mat,axis=0)
# min value in each column

array([2, 1, 6])

## 1.8 Average, Variance and Standard deviation

In [117]:
# Descriptive statistics about of array

In [118]:
mats = np.array([[9,5,7],
                 [4,1,6],
                 [2,3,0]])
mats

array([[9, 5, 7],
       [4, 1, 6],
       [2, 3, 0]])

In [119]:
avg = np.mean(mats)
avg

4.111111111111111

In [120]:
variance = np.var(mats)
variance

7.65432098765432

In [121]:
sd = np.std(mats)
sd

2.7666443551086073

In [122]:
avg = np.mean(mats, axis=1)
avg
# average of each row elements

array([7.        , 3.66666667, 1.66666667])

In [123]:
avg = np.mean(mats, axis=0)
avg
# Average of each column elements 

array([5.        , 3.        , 4.33333333])

## 1.9 Reshaping arrays

In [124]:
re_mat = np.array([[9,5,7],
                 [4,1,6],
                 [2,3,0],
                 [11,15,7],
                 [6,8,2],
                 [5,9,7]])
re_mat

array([[ 9,  5,  7],
       [ 4,  1,  6],
       [ 2,  3,  0],
       [11, 15,  7],
       [ 6,  8,  2],
       [ 5,  9,  7]])

In [125]:
re_mat.size

18

In [126]:
resp_mat = re_mat.reshape(9,2)
resp_mat

array([[ 9,  5],
       [ 7,  4],
       [ 1,  6],
       [ 2,  3],
       [ 0, 11],
       [15,  7],
       [ 6,  8],
       [ 2,  5],
       [ 9,  7]])

In [127]:
resp_mat.size

18

In [128]:
oneCol_mat = resp_mat.reshape(-1,1)
oneCol_mat
# negative value in reshape function means we can change in any way we want
# here it creates 1 column and as many rows as needed

array([[ 9],
       [ 5],
       [ 7],
       [ 4],
       [ 1],
       [ 6],
       [ 2],
       [ 3],
       [ 0],
       [11],
       [15],
       [ 7],
       [ 6],
       [ 8],
       [ 2],
       [ 5],
       [ 9],
       [ 7]])

In [129]:
oneRow_mat = resp_mat.reshape(1,-1)
oneRow_mat
# 1 row and as many columns as required

array([[ 9,  5,  7,  4,  1,  6,  2,  3,  0, 11, 15,  7,  6,  8,  2,  5,
         9,  7]])

In [130]:
twoRow_mat = resp_mat.reshape(2,-1)
twoRow_mat
# 2 rows and as many columns as required

array([[ 9,  5,  7,  4,  1,  6,  2,  3,  0],
       [11, 15,  7,  6,  8,  2,  5,  9,  7]])

## 1.10 Transposing a vector or a matrix

In [131]:
np.array([1,2,3,5]).T
# vector can not be transposed because its a collection of values

array([1, 2, 3, 5])

In [132]:
np.array([[1,2,3,5]]).T
# transpose of a mtrix is where the the columns and rows are swapped 

array([[1],
       [2],
       [3],
       [5]])

## 1.11 Falttening a matrix

In [133]:
# transforms matrix into on-dimensional array
mat_flat = np.array([[1,2],
                    [2,3],
                    [3,4]])
mat_flat.flatten()

array([1, 2, 2, 3, 3, 4])

In [134]:
# flatten is a simple way of creating a 1-D array like resp_mat.reshape(-1,1)

## 1.12 Finding the rank of the matrix

In [135]:
rk_mat = np.array([[9,5,7],
                 [4,1,6],
                 [2,3,7]])
rank = np.linalg.matrix_rank(rk_mat)
rank

3

## 1.13 Determinant of a matrix

In [136]:
det = np.linalg.det(rk_mat)
det

-108.99999999999997

## 1.14 Diagonal of a matrix

In [137]:
diag = np.diagonal(rk_mat)
diag

array([9, 1, 7])

In [138]:
rk_mat.diagonal()

array([9, 1, 7])

In [139]:
rk_mat.diagonal(offset=1)

array([5, 6])

In [140]:
rk_mat.diagonal(offset=-1)

array([4, 3])

In [141]:
rk_mat.diagonal(offset=2)

array([7])

## 1.15 trace of a matrix

In [142]:
rk_mat.trace()
# sum of the diagonal elements

17

In [143]:
sum(rk_mat.diagonal())

17

## 1.16 Eigen values and Eigen vectors

In [144]:
eg_mat = np.array([[9,5,7],
                 [4,1,6],
                 [2,3,7]])

In [145]:
eigenvalues, eigenvectors = np.linalg.eig(eg_mat)
# caluclataes eigenvalues and eigenvectors

In [146]:
eigenvalues

array([14.64891671,  4.14584826, -1.79476497])

In [147]:
eigenvectors

array([[-0.83047309, -0.82756123,  0.26388016],
       [-0.40943044,  0.01789534, -0.92965711],
       [-0.37773159,  0.56109016,  0.25710875]])

In [148]:
# eigenvalues = np.linalg.eig(eg_mat)
# eigenvalues

In [149]:
# eigenvectors = np.linalg.eig(eg_mat)
# eigenvectors

In [150]:
egvalues = np.linalg.eigvals(eg_mat)
egvalues

array([14.64891671,  4.14584826, -1.79476497])

## 1.7 Dot products 

In [151]:
vec_a = np.array([1,2,3])
vec_b = np.array([4,5,6])

In [152]:
np.dot(vec_a,vec_b)

32

In [153]:
vec_a @ vec_b

32

## 1.8 Adding and subtracting matrices

In [154]:
mat_a = np.array([[9,5,7],
                 [4,1,6],
                 [2,3,7]])
mat_b = np.array([[4,2,2],
                 [9,1,1],
                 [1,8,6]])

In [155]:
mat_a + mat_b

array([[13,  7,  9],
       [13,  2,  7],
       [ 3, 11, 13]])

In [156]:
np.add(mat_a, mat_b)

array([[13,  7,  9],
       [13,  2,  7],
       [ 3, 11, 13]])

In [157]:
mat_a - mat_b

array([[ 5,  3,  5],
       [-5,  0,  5],
       [ 1, -5,  1]])

In [158]:
np.subtract(mat_a, mat_b)

array([[ 5,  3,  5],
       [-5,  0,  5],
       [ 1, -5,  1]])

## 1.19 Multiplying matrices

In [159]:
np.dot(mat_a, mat_b)

array([[88, 79, 65],
       [31, 57, 45],
       [42, 63, 49]])

In [160]:
mat_a @ mat_b

array([[88, 79, 65],
       [31, 57, 45],
       [42, 63, 49]])

In [161]:
mat_a * mat_b

array([[36, 10, 14],
       [36,  1,  6],
       [ 2, 24, 42]])

## 1.20 Inverting matrix

In [162]:
inr = np.linalg.inv(mat_a)
inr

array([[ 0.10091743,  0.12844037, -0.21100917],
       [ 0.14678899, -0.44954128,  0.23853211],
       [-0.09174312,  0.1559633 ,  0.10091743]])

In [163]:
# the multiplication of a matrix and its inverse is an Identity matrix
mat_b @ inr

array([[ 0.51376147, -0.0733945 , -0.16513761],
       [ 0.96330275,  0.86238532, -1.55963303],
       [ 0.72477064, -2.53211009,  2.30275229]])

## 1.21 Generating random values

In [173]:
# set seed
np.random.seed(0)
# by setting seed to zero, the generated random numbers will take 0 as starting value

In [200]:
np.random.random(4)
# generating 4 random values between 0 and 1
# this gives float

array([0.70373728, 0.28847644, 0.43328806, 0.75610669])

In [181]:
# for generating integers 
np.random.randint(0, 10, 4)
# 4 integers between 0 and 10

array([9, 9, 0, 4])

In [171]:
# 3 random numbers from "Normal distribution" with mean 2, standard deviation 5
np.random.normal(2,5,3)

array([-0.35385502,  6.86507998, -4.39074559])

In [172]:
# 3 random numbers from "Logistic distribution" with mean 2, standard deviation 5
np.random.logistic(2,5,3)

array([17.53190133, -7.06189779, 11.50865248])